language: en
version: "3.1"
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
- name: EntitySynonymMapper

policies:
- name: MemoizationPolicy
- name: RulePolicy
assistant_id: 20250121-142532-faded-market
